[package]
name = "wgpu-example-shader"
version = "0.1.0"
authors = ["Embark <opensource@embark-studios.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = { path = "../../spirv-std" }
