[package]
name = "example-runner-ash"
version = "0.1.0"
authors = ["Embark <opensource@embark-studios.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

# See rustc_codegen_spirv/Cargo.toml for details on these features
[features]

[dependencies]
shared = { path = "../../shaders/shared" }
ash = "0.31"
ash-window = "0.5"
cfg-if = "1.0.0"
structopt = "0.3.20"
winit = "0.23.0"

[target.'cfg(target_os = "macos")'.dependencies]
ash-molten = { version = "0.7", features = ["pre-built"] }

[build-dependencies]
spirv-builder = { path = "../../../crates/spirv-builder", default-features = false }
