[package]
name = "example-runner-wgpu"
version = "0.4.0-alpha.5"
authors = ["Embark <opensource@embark-studios.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["lib", "cdylib"]

# See rustc_codegen_spirv/Cargo.toml for details on these features
[features]
default = ["use-compiled-tools"]
use-installed-tools = ["spirv-builder/use-installed-tools"]
use-compiled-tools = ["spirv-builder/use-compiled-tools"]

[dependencies]
cfg-if = "1.0.0"
shared = { path = "../../shaders/shared" }
futures = { version = "0.3", default-features = false, features = ["std", "executor"] }
wgpu = "0.7.0"
winit = { version = "0.24", features = ["web-sys"] }
clap = "3.0.0-beta.2"
strum = { version = "0.20", default_features = false, features = ["derive"] }

[build-dependencies]
spirv-builder = { path = "../../../crates/spirv-builder", default-features = false }

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu-subscriber = "0.1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = "=0.3.46"
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
wasm-bindgen-futures = "0.4.18"
