[package]
name = "example-runner-wgpu"
version = "0.1.0"
authors = ["Embark <opensource@embark-studios.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

# See rustc_codegen_spirv/Cargo.toml for details on these features
[features]
default = ["use-compiled-tools", "hot-reload"]
use-installed-tools = ["spirv-builder/use-installed-tools"]
use-compiled-tools = ["spirv-builder/use-compiled-tools"]
hot-reload = ["notify"]

[dependencies]
wgpu = "0.6.0"
futures = { version = "0.3", default-features = false, features = ["std", "executor"] }
winit = { version = "0.23", features = ["web-sys"] }
notify = { version = "5.0.0-pre.4", optional = true }

[build-dependencies]
spirv-builder = { path = "../../../spirv-builder", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu-subscriber = "0.1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = "=0.3.39"
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
wasm-bindgen-futures = "0.4.18"
