[package]
name = "shared"
version = "0.4.0-alpha.9"
authors = ["Embark <opensource@embark-studios.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
spirv-std = { path = "../../../crates/spirv-std", features = ["glam"] }
bytemuck = { version = "1.6.3", features = ["derive"] }
